# Generated by Django 4.2.6 on 2023-10-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='category',
        ),
    ]
