# Generated by Django 4.2.6 on 2023-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
